(function(c){"object"===typeof module&&"object"===typeof module.exports?c(require("jquery")):"function"===typeof define&&define.amd?define([],c(window.jQuery)):c(window.jQuery)})(function(c){if(!c)return console.warn("Unslider needs jQuery");c.Unslider=function(e,g){var a=this;a._="unslider";a.defaults={autoplay:!1,delay:3E3,speed:750,easing:"swing",keys:{prev:37,next:39},nav:!0,arrows:{prev:'\x3ca class\x3d"'+a._+'-arrow prev"\x3ePrev\x3c/a\x3e',next:'\x3ca class\x3d"'+a._+'-arrow next"\x3eNext\x3c/a\x3e'},
animation:"horizontal",selectors:{container:"ul:first",slides:"li"},animateHeight:!1,activeClass:a._+"-active",swipe:!0,swipeThreshold:0.2};a.$context=e;a.options={};a.$parent=null;a.$container=null;a.$slides=null;a.$nav=null;a.$arrows=[];a.total=0;a.current=0;a.prefix=a._+"-";a.eventSuffix="."+a.prefix+~~(2E3*Math.random());a.interval=null;a.init=function(b){a.options=c.extend({},a.defaults,b);a.$container=a.$context.find(a.options.selectors.container).addClass(a.prefix+"wrap");a.$slides=a.$container.children(a.options.selectors.slides);
a.setup();c.each(["nav","arrows","keys","infinite"],function(b,f){a.options[f]&&a["init"+c._ucfirst(f)]()});jQuery.event.special.swipe&&a.options.swipe&&a.initSwipe();a.options.autoplay&&a.start();a.calculateSlides();a.$context.trigger(a._+".ready");return a.animate(a.options.index||a.current,"init")};a.setup=function(){a.$context.addClass(a.prefix+a.options.animation).wrap('\x3cdiv class\x3d"'+a._+'" /\x3e');a.$parent=a.$context.parent("."+a._);"static"===a.$context.css("position")&&a.$context.css("position",
"relative");a.$context.css("overflow","hidden")};a.calculateSlides=function(){a.$slides=a.$container.children(a.options.selectors.slides);a.total=a.$slides.length;if("fade"!==a.options.animation){var b="width";"vertical"===a.options.animation&&(b="height");a.$container.css(b,100*a.total+"%").addClass(a.prefix+"carousel");a.$slides.css(b,100/a.total+"%")}};a.start=function(){a.interval=setTimeout(function(){a.next()},a.options.delay);return a};a.stop=function(){clearTimeout(a.interval);return a};a.initNav=
function(){var b=c('\x3cnav class\x3d"'+a.prefix+'nav"\x3e\x3col /\x3e\x3c/nav\x3e');a.$slides.each(function(d){var f=this.getAttribute("data-nav")||d+1;c.isFunction(a.options.nav)&&(f=a.options.nav.call(a.$slides.eq(d),d,f));b.children("ol").append('\x3cli data-slide\x3d"'+d+'"\x3e'+f+"\x3c/li\x3e")});a.$nav=b.insertAfter(a.$context);a.$nav.find("li").on("click"+a.eventSuffix,function(){var b=c(this).addClass(a.options.activeClass);b.siblings().removeClass(a.options.activeClass);a.animate(b.attr("data-slide"))})};
a.initArrows=function(){!0===a.options.arrows&&(a.options.arrows=a.defaults.arrows);c.each(a.options.arrows,function(b,d){a.$arrows.push(c(d).insertAfter(a.$context).on("click"+a.eventSuffix,a[b]))})};a.initKeys=function(){!0===a.options.keys&&(a.options.keys=a.defaults.keys);c(document).on("keyup"+a.eventSuffix,function(b){c.each(a.options.keys,function(d,f){b.which===f&&c.isFunction(a[d])&&a[d].call(a)})})};a.initSwipe=function(){var b=a.$slides.width();if("fade"!==a.options.animation)a.$container.on({movestart:function(b){if(b.distX>
b.distY&&b.distX<-b.distY||b.distX<b.distY&&b.distX>-b.distY)return!!b.preventDefault();a.$container.css("position","relative")},move:function(d){a.$container.css("left",-(100*a.current)+100*d.distX/b+"%")},moveend:function(d){if(Math.abs(d.distX)/b>a.options.swipeThreshold)a[0>d.distX?"next":"prev"]();else a.$container.animate({left:-(100*a.current)+"%"},a.options.speed/2)}})};a.initInfinite=function(){var b=["first","last"];c.each(b,function(d,c){try{a.$slides.push.apply(a.$slides,a.$slides.filter(':not(".'+
a._+'-clone")')[c]().clone().addClass(a._+"-clone")["insert"+(0===d?"After":"Before")](a.$slides[b[~~!d]]()))}catch(e){}})};a.destroyArrows=function(){c.each(a.$arrows,function(a,d){d.remove()})};a.destroySwipe=function(){a.$container.off("movestart move moveend")};a.destroyKeys=function(){c(document).off("keyup"+a.eventSuffix)};a.setIndex=function(b){0>b&&(b=a.total-1);a.current=Math.min(Math.max(0,b),a.total-1);a.options.nav&&a.$nav.find('[data-slide\x3d"'+a.current+'"]')._active(a.options.activeClass);
a.$slides.eq(a.current)._active(a.options.activeClass);return a};a.animate=function(b,d){"first"===b&&(b=0);"last"===b&&(b=a.total);if(isNaN(b))return a;a.options.autoplay&&a.stop().start();a.setIndex(b);a.$context.trigger(a._+".change",[b,a.$slides.eq(b)]);var f="animate"+c._ucfirst(a.options.animation);if(c.isFunction(a[f]))a[f](a.current,d);return a};a.next=function(){var b=a.current+1;b>=a.total&&(b=0);return a.animate(b,"next")};a.prev=function(){return a.animate(a.current-1,"prev")};a.animateHorizontal=
function(b){var d="left";"rtl"===a.$context.attr("dir")&&(d="right");a.options.infinite&&a.$container.css("margin-"+d,"-100%");return a.slide(d,b)};a.animateVertical=function(b){a.options.animateHeight=!0;a.options.infinite&&a.$container.css("margin-top",-a.$slides.outerHeight());return a.slide("top",b)};a.slide=function(b,d){a.animateHeight(d);if(a.options.infinite){var c;d===a.total-1&&(c=a.total-3,d=-1);d===a.total-2&&(c=0,d=a.total-2);"number"===typeof c&&(a.setIndex(c),a.$context.on(a._+".moved",
function(){a.current===c&&a.$container.css(b,-(100*c)+"%").off(a._+".moved")}))}var e={};e[b]=-(100*d)+"%";return a._move(a.$container,e)};a.animateFade=function(b){a.animateHeight(b);b=a.$slides.eq(b).addClass(a.options.activeClass);a._move(b.siblings().removeClass(a.options.activeClass),{opacity:0});a._move(b,{opacity:1},!1)};a.animateHeight=function(b){a.options.animateHeight&&a._move(a.$context,{height:a.$slides.eq(b).outerHeight()},!1)};a._move=function(b,c,e,g){!1!==e&&(e=function(){a.$context.trigger(a._+
".moved")});return b._move(c,g||a.options.speed,a.options.easing,e)};return a.init(g)};c.fn._active=function(c){return this.addClass(c).siblings().removeClass(c)};c._ucfirst=function(c){return(c+"").toLowerCase().replace(/^./,function(c){return c.toUpperCase()})};c.fn._move=function(){this.stop(!0,!0);return c.fn[c.fn.velocity?"velocity":"animate"].apply(this,arguments)};c.fn.unslider=function(e){return this.each(function(){var g=c(this);if("string"===typeof e&&g.data("unslider")){e=e.split(":");
var a=g.data("unslider")[e[0]];if(c.isFunction(a))return a.apply(g,e[1]?e[1].split(","):null)}return g.data("unslider",new c.Unslider(g,e))})}});