var websocket=null;
_WSServ={initWebSocket:function(b){if(!websocket){var a=snBase.account.url.webSocketURL;a&&(0<a.indexOf("${UserCode}")?(a=a.replace("${UserCode}",b),a=a.replace("${RSESSIONID}",getRsessionId()),a=snBase.account.url.accessKey?a.replace("${AccessKey}",snBase.account.url.accessKey):a.replace("${AccessKey}","\x3cNULL\x3e")):(a=a+("?dest\x3d"+b)+("\x26RSESSIONID\x3d"+getRsessionId()),snBase.account.url.accessKey&&(a+="\x26AccessKey\x3d"+snBase.account.url.accessKey)),websocket=new WebSocket(a),websocket.onmessage=
function(a){onMessage(a)},websocket.onerror=function(a){onError(a)},websocket.onopen=function(){})}}};function getRsessionId(){if(document.cookie)for(var b=document.cookie.split(";"),a=0;a<b.length;a++){var d=b[a].trim();if(0==d.indexOf("RSESSIONID\x3d"))return d.substring(11)}return null}function onMessage(b){b=parse(b.data);writeToScreen(b);postWarnQueryMessage(b)}
function postWarnQueryMessage(b){"msg.sysmsg_receive"==b.purpose&&$("#user_center_iframe")[0].contentWindow.postMessage({msgtype:"IFrameWarnQuery"},"*")}function onError(){}var msgs=[];
function writeToScreen(b){if("msg.sysmsg_receive"==b.purpose){var a=parse(b.message);msgs.push(a);b=window.document.getElementsByClassName("message-main-div");if(0<b.length){var d=b[0].getElementsByClassName("message-warning"),c=d[0].getElementsByClassName("message-list");if(3==c.length&&3<msgs.length){var e=getWarnLastDOM(c[0]);d[0].removeChild(e)}a=buildOneMsgDOM(window.document.body,a);d[0].insertBefore(a,c[0]);b[0].getElementsByClassName("view-all")[0].textContent="\u67e5\u770b\u5168\u90e8\uff08"+
msgs.length+"\uff09"}else buildMainMessageDOM(a),messageWarn()}}function messageWarn(){function b(){1200<$(window).width()?(d.show(),c.hide()):(d.hide(),c.show())}var a=$(".message-warning"),d=$(".message-scale"),c=$(".smallScreen");b();$(".message-close").click(function(){a.hide();b()});d.click(function(){a.show();d.hide();c.hide()})}
function buildMainMessageDOM(b){var a=createChild(window.document.body,"div","message-main-div");buildMessageScale(a);a=createChild(a,"div","message-warning");createChild(a,"h2").textContent="\u6d88\u606f\u9884\u8b66";var d=createChild(a,"a","message-close");d.href="###";createChild(d,"i","icon-del3");buildOneMsgDOM(a,b);b=createChild(a,"p","message-opera");a=createChild(b,"a","ignore-all");a.textContent="\u5ffd\u7565\u5168\u90e8";a.href="###";a.onclick=function(){closeMessage(this)};b=createChild(b,
"a","view-all");b.textContent="\u67e5\u770b\u5168\u90e8\uff081\uff09";b.href="###";b.onclick=function(){postWarnOpenMessage({warnfuncid:"27.TS.02.40.10"});closeMessage(this)}}
function setMsgReaded(b){b&&$.ajax({async:!0,type:"POST",dataType:"json",url:snBase.account.url.setMsgReaded,data:b,success:function(a){"success"==a.result?(a={msgtype:"IFrameMsgReaded",sysmsgid:a.sysmsgid},$("#user_center_iframe")[0].contentWindow.postMessage(a,"*")):"error"==a.result&&(showUrl=snBase.account.url.errorUrl,$(window.parent.document).find("#user_center_iframe").attr("src",showUrl),$(".m-main").addClass("m-main2"))}})}
function postWarnOpenMessage(b){b&&$.ajax({async:!0,type:"POST",dataType:"json",url:snBase.account.url.getWarnUrl,data:b,success:function(a){"success"==a.result?window.open(a.url,"_blank"):"error"==a.result&&(showUrl=snBase.account.url.errorUrl,$(window.parent.document).find("#user_center_iframe").attr("src",showUrl),$(".m-main").addClass("m-main2"))}})}function closeMessage(b){if(b=getParentByClass(b,"message-main-div"))window.document.body.removeChild(b),msgs.splice(0,msgs.length)}
function buildMessageScale(b){var a=createChild(b,"a","message-scale");createChild(a,"i","icon-messageScale");a=createChild(a,"div","message-view");createChild(a,"i","icon-messageG");createChild(a,"span").textContent="\u70b9\u51fb\u67e5\u770b";b=createChild(b,"a","message-scale smallScreen");createChild(b,"i","icon-messageScale2");b=createChild(b,"div","message-view");createChild(b,"i","icon-messageArr")}
function buildOneMsgDOM(b,a){var d=createChild(b,"div","message-list");d.setAttribute("sysmsgid",a.sysmsgid);var c=createChild(d,"dl"),e=createChild(c,"dt");createChild(e,"i","icon-messageY");var c=createChild(c,"dd","message-m"),e=createChild(c,"div","message-d fl"),f=createChild(e,"span"),g=a.title?a.title:a.subject;f.textContent=g?g:"\u6d88\u606f\u63d0\u9192";createChild(e,"i","icon-msg-smallbellgreen");e=createChild(e,"a","message-detail");e.href="###";isNeedOpenDetail(a)&&(e.onclick=function(){postWarnOpenMessage(a);
setMsgReaded(a);knowMessage(this)});f=a.message?a.message:a.textContent;e.title=f?f:"\u60a8\u6709\u4e00\u6761\u63d0\u9192\u6d88\u606f\uff01";e.textContent=f?f:"\u60a8\u6709\u4e00\u6761\u63d0\u9192\u6d88\u606f\uff01";c=createChild(c,"div","message-btn fr");e=createChild(c,"a","message-know");e.href="###";e.textContent="\u77e5\u9053\u4e86";e.onclick=function(){setMsgReaded(a);knowMessage(this)};isNeedOpenDetail(a)&&(c=createChild(c,"a","message-enter"),c.href="###",c.textContent="\u8fdb\u5165",c.onclick=
function(){postWarnOpenMessage(a);setMsgReaded(a);knowMessage(this)});c=createChild(d,"p","message-b");createChild(c,"span").textContent="\u53d1\u9001\u4eba\uff1a"+a.fname;c=createChild(c,"a","message-time");c.textContent="\u521a\u521a";c.href="###";return d}function isNeedOpenDetail(b){return b.warnparams&&0<b.warnparams.indexOf("taskid")||b.warnfuncid||b.warnsheetcode?!0:!1}
function knowMessage(b){var a=getParentByClass(b,"message-main-div");if(1==msgs.length)a&&closeMessage(b);else{b=getParentByClass(b,"message-list");var d=getParentByClass(b,"message-warning");if(d){var c=getWarnLastDOM(b);removeMsgs(b.getAttribute("sysmsgid"));if(3<=msgs.length){var e=buildOneMsgDOM(window.document.body,msgs[msgs.length-3]);d.insertBefore(e,c.nextSibling)}d.removeChild(b);a.getElementsByClassName("view-all")[0].textContent="\u67e5\u770b\u5168\u90e8\uff08"+msgs.length+"\uff09"}}}
function getWarnLastDOM(b){var a=b.nextSibling;return!a||"message-list"!=a.className?b:getWarnLastDOM(a)}function removeMsgs(b){if(!msgs||0==msgs.length)return null;for(var a=0;a<msgs.length;a++)if(msgs[a].sysmsgid==b){msgs.splice(a,1);break}}function getParentByClass(b,a){return!a||!b.parentElement?null:b.parentElement.className==a?b.parentElement:getParentByClass(b.parentElement,a)}
function parse(b){if(null==b)return null;b=b.trim();return 2<b.length&&"{"==b.charAt(0)&&"}"==b.charAt(b.length-1)?eval("("+b+")"):eval(b)}function createChild(b,a,d){a=document.createElement(a);d&&(a.className=d);b&&b.appendChild(a);return a};