(function(d){"function"===typeof define&&define.amd?define(["jquery"],d):"undefined"!==typeof module&&null!==module&&module.exports?module.exports=d:d(jQuery)})(function(d,i){function m(a){function b(){d?(c(),G(b),k=!0,d=!1):k=!1}var c=a,d=!1,k=!1;this.kick=function(){d=!0;k||b()};this.end=function(a){var b=c;a&&(k?(c=d?function(){b();a()}:a,d=!0):a())}}function o(){return!0}function n(){return!1}function h(a){a.preventDefault()}function c(a){r[a.target.tagName.toLowerCase()]||a.preventDefault()}
function g(a,b){var d,c;if(a.identifiedTouch)return a.identifiedTouch(b);d=-1;for(c=a.length;++d<c;)if(a[d].identifier===b)return a[d]}function s(a,b){var d=g(a.changedTouches,b.identifier);if(d&&!(d.pageX===b.pageX&&d.pageY===b.pageY))return d}function j(a){t(a,a.data,a,u)}function v(){u()}function u(){e(document,l.move,j);e(document,l.cancel,v)}function w(a){var b=a.data,d=s(a,b);d&&t(a,b,d,x)}function y(a){var b=a.data;g(a.changedTouches,b.identifier)&&x(b.identifier)}function x(a){e(document,
"."+a,w);e(document,"."+a,y)}function t(a,b,c,g){var k=c.pageX-b.startX,e=c.pageY-b.startY;if(!(k*k+e*e<z*z)){var f,h;f=a.targetTouches;h=a.timeStamp-b.timeStamp;b.type="movestart";b.distX=k;b.distY=e;b.deltaX=k;b.deltaY=e;b.pageX=c.pageX;b.pageY=c.pageY;b.velocityX=k/h;b.velocityY=e/h;b.targetTouches=f;b.finger=f?f.length:1;b._handled=H;b._preventTouchmoveDefault=function(){a.preventDefault()};d.event.trigger(b,void 0,b.target);g(b.identifier)}}function H(){this._handled=o;return!1}function A(a){a._handled()}
function B(a){var b=a.data.timer;a.data.touch=a;a.data.timeStamp=a.timeStamp;b.kick()}function C(a){var b=a.data.event;a=a.data.timer;e(document,l.move,B);e(document,l.end,C);D(b,a,function(){setTimeout(function(){e(b.target,"click",n)},0)})}function E(a){var b=a.data.event,d=a.data.timer,c=s(a,b);c&&(a.preventDefault(),b.targetTouches=a.targetTouches,a.data.touch=c,a.data.timeStamp=a.timeStamp,d.kick())}function F(a){var b=a.data.event,d=a.data.timer;g(a.changedTouches,b.identifier)&&(e(document,
"."+b.identifier,E),e(document,"."+b.identifier,F),D(b,d))}function D(a,b,c){b.end(function(){a.type="moveend";d.event.trigger(a,void 0,a.target);return c&&c()})}var z=6,f=d.event.add,e=d.event.remove,G=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){return window.setTimeout(function(){a()},25)},r={textarea:!0,input:!0,select:!0,button:!0},l={move:"mousemove",cancel:"mouseup dragstart",
end:"mouseup"};d.event.special.movestart={setup:function(){f(this,"movestart.move",A);return!0},teardown:function(){e(this,"dragstart drag",h);e(this,"mousedown touchstart",c);e(this,"movestart",A);return!0},add:function(a){"move"===a.namespace||"moveend"===a.namespace||(f(this,"dragstart."+a.guid+" drag."+a.guid,h,i,a.selector),f(this,"mousedown."+a.guid,c,i,a.selector))},remove:function(a){"move"===a.namespace||"moveend"===a.namespace||(e(this,"dragstart."+a.guid+" drag."+a.guid),e(this,"mousedown."+
a.guid))},_default:function(a){function b(){var b=c,f=e.touch,g=e.timeStamp-b.timeStamp;b.type="move";b.distX=f.pageX-b.startX;b.distY=f.pageY-b.startY;b.deltaX=f.pageX-b.pageX;b.deltaY=f.pageY-b.pageY;b.velocityX=0.3*b.velocityX+0.7*b.deltaX/g;b.velocityY=0.3*b.velocityY+0.7*b.deltaY/g;b.pageX=f.pageX;b.pageY=f.pageY;d.event.trigger(c,void 0,a.target)}var c,e;a._handled()&&(c={target:a.target,startX:a.startX,startY:a.startY,pageX:a.pageX,pageY:a.pageY,distX:a.distX,distY:a.distY,deltaX:a.deltaX,
deltaY:a.deltaY,velocityX:a.velocityX,velocityY:a.velocityY,timeStamp:a.timeStamp,identifier:a.identifier,targetTouches:a.targetTouches,finger:a.finger},e={event:c,timer:new m(b),touch:i,timeStamp:i},a.identifier===i?(f(a.target,"click",n),f(document,l.move,B,e),f(document,l.end,C,e)):(a._preventTouchmoveDefault(),f(document,"touchmove."+a.identifier,E,e),f(document,"touchend."+a.identifier,F,e)))}};d.event.special.move={setup:function(){f(this,"movestart.move",d.noop)},teardown:function(){e(this,
"movestart.move",d.noop)}};d.event.special.moveend={setup:function(){f(this,"movestart.moveend",d.noop)},teardown:function(){e(this,"movestart.moveend",d.noop)}};f(document,"mousedown.move",function(a){1===a.which&&(!a.ctrlKey&&!a.altKey)&&(a={target:a.target,startX:a.pageX,startY:a.pageY,timeStamp:a.timeStamp},f(document,l.move,j,a),f(document,l.cancel,v,a))});f(document,"touchstart.move",function(a){var b;r[a.target.tagName.toLowerCase()]||(b=a.changedTouches[0],a={target:b.target,startX:b.pageX,
startY:b.pageY,timeStamp:a.timeStamp,identifier:b.identifier},f(document,"touchmove."+b.identifier,w,a),f(document,"touchend."+b.identifier,y,a))});if("function"===typeof Array.prototype.indexOf)for(var p=["changedTouches","targetTouches"],q=p.length;q--;)-1===d.event.props.indexOf(p[q])&&d.event.props.push(p[q])});
(function(d){"function"===typeof define&&define.amd?define(["jquery",void 0,"jquery.event.move"],d):"undefined"!==typeof module&&null!==module&&module.exports?module.exports=d:d(jQuery)})(function(d){function i(c){var g,i,j;g=c.currentTarget.offsetWidth;i=c.currentTarget.offsetHeight;j={distX:c.distX,distY:c.distY,velocityX:c.velocityX,velocityY:c.velocityY,finger:c.finger};if(c.distX>c.distY)if(c.distX>-c.distY){if(c.distX/g>h.threshold||1<c.velocityX*c.distX/g*h.sensitivity)j.type="swiperight",
d.event.trigger(j,void 0,c.currentTarget)}else{if(-c.distY/i>h.threshold||1<c.velocityY*c.distY/g*h.sensitivity)j.type="swipeup",d.event.trigger(j,void 0,c.currentTarget)}else if(c.distX>-c.distY){if(c.distY/i>h.threshold||1<c.velocityY*c.distY/g*h.sensitivity)j.type="swipedown",d.event.trigger(j,void 0,c.currentTarget)}else if(-c.distX/g>h.threshold||1<c.velocityX*c.distX/g*h.sensitivity)j.type="swipeleft",d.event.trigger(j,void 0,c.currentTarget)}function m(c){var g=d.data(c,"event_swipe");g||(g=
{count:0},d.data(c,"event_swipe",g));return g}var o=d.event.add,n=d.event.remove,h={threshold:0.4,sensitivity:6};d.event.special.swipe=d.event.special.swipeleft=d.event.special.swiperight=d.event.special.swipeup=d.event.special.swipedown={setup:function(c){c=m(this);if(!(0<c.count++))return o(this,"moveend",i),!0},teardown:function(){if(!(0<--m(this).count))return n(this,"moveend",i),!0},settings:h}});