function isChinese(a){return!/^[\u4e00-\u9fa5_a-zA-Z0-9]{1,6}$/.exec(a)?!1:!0}function isMail(a){return/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(a)}function isNum(a){return/^[1-9]\d*$/.test(a)}function isTeshu(a){return/^.*[@!#$%^&*()]+.*$/.test(a)}function isKong(a){return/(^\s+)|(\s+$)/g.test(a)}function isMobile(a){return/^1(3|4|5|7|8)\d{9}$/.test(a)}function isPostCode(a){return/^[1-9]\d{5}$/.test(a)}
function isUnit(a){return/^[\u2E80-\u2EFF\u2F00-\u2FDF\u3000-\u303F\u31C0-\u31EF\u3200-\u32FF\u3300-\u33FF\u3400-\u4DBF\u4DC0-\u4DFF\u4E00-\u9FBF\uF900-\uFAFF\uFE30-\uFE4F\uFF00-\uFFEF]+$/.test(a)}function isPhone(a){return/^\d{3}-\d{8}|\d{4}-\d{7}$/.test(a)}function isNumber(a){if(""==trim(a))return!1;for(var c=0;c<a.length;c++){var b=a.charAt(c);if("0"!=b&&"1"!=b&&"2"!=b&&"3"!=b&&"4"!=b&&"5"!=b&&"6"!=b&&"7"!=b&&"8"!=b&&"9"!=b)return!1}return!0}function isEmailNum(){}
function isFax(a){return/^[+]{0,1}(\d){1,3}[ ]?([-]?((\d)|[ ]){1,12})+$/.test(a)}function getByteLen(a){for(var c=0,b=0;b<a.length;b++)c=null!=a[b].match(/[^\x00-\xff]/ig)?c+2:c+1;return c}function trim(a){return a.replace(/(^\s*)|(\s*$)/g,"")}
function unit_blur(){var a=$("#compname").val();""==trim(a)?($("#compname_span").addClass("error-tip"),$("#compname_span").html("\u4f01\u4e1a\u540d\u79f0\u4e0d\u80fd\u4e3a\u7a7a\uff01")):($("#compname_span").removeClass("error-tip"),$("#compname_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e"))}
function compaddr_blur(){var a=$("#compaddr").val();""==trim(a)?($("#compaddr_span").addClass("error-tip"),$("#compaddr_span").html("\u516c\u53f8\u5730\u5740\u4e0d\u80fd\u4e3a\u7a7a\uff01")):($("#compaddr_span").removeClass("error-tip"),$("#compaddr_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e"))}function password_focus(){$("#upassword_span").removeClass("error-tip");$("#upassword_span").html("")}
function password_blur(){var a=$("#upassword").val();""==trim(a)?($("#upassword_span").addClass("error-tip"),$("#upassword_span").html("\u5bc6\u7801\u4e0d\u80fd\u4e3a\u7a7a")):(a=a.length,6<=a&&26>=a?($("#upassword_span").removeClass("error-tip"),$("#upassword_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e")):($("#upassword_span").addClass("error-tip"),$("#upassword_span").html("\u8bf7\u8f93\u51656-26\u4f4d\u5b57\u7b26")))}
function password2_focus(){$("#upassword2_span").removeClass("error-tip");$("#upassword2_span").html("")}
function password2_blur(){var a=$("#upassword2").val();""==trim(a)?($("#upassword2_span").addClass("error-tip"),$("#upassword2_span").html("\u5bc6\u7801\u4e0d\u80fd\u4e3a\u7a7a")):a===$("#upassword").val()?($("#upassword2_span").removeClass("error-tip"),$("#upassword2_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e")):($("#upassword2_span").addClass("error-tip"),$("#upassword2_span").html("\u8f93\u5165\u4e0d\u4e00\u81f4\uff0c\u8bf7\u91cd\u8bd5"))}
function email_blur(a){a=a.val();""==trim(a)?($("#conemail_span").addClass("error-tip"),$("#conemail_span").html("\u8054\u7cfb\u4eba\u90ae\u7bb1\u4e0d\u80fd\u4e3a\u7a7a")):isMail(a)?ajaxCheckData(verifyDataUserUrl,"conemail",a):($("#conemail_span").addClass("error-tip"),$("#conemail_span").html("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u90ae\u7bb1"))}
function regcity_blur(){var a=$("#regcity").val();""==trim(a)?($("#regcity_span").addClass("error-tip"),$("#regcity_span").html("\u6ce8\u518c\u5730\u4e0d\u80fd\u4e3a\u7a7a")):($("#regcity_span").removeClass("error-tip"),$("#regcity_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e"))}function langname1_focus(){$("#langname1_span").removeClass("error-tip");$("#langname1_span").html("")}
function postcode_blur(){var a=$("#postcode").val();""==trim(a)?($("#postcode_span").addClass("error-tip"),$("#postcode_span").html("\u90ae\u653f\u7f16\u7801\u4e0d\u80fd\u4e3a\u7a7a")):isPostCode(a)?($("#postcode_span").removeClass("error-tip"),$("#postcode_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e")):($("#postcode_span").addClass("error-tip"),$("#postcode_span").html("\u586b\u5199\u6b63\u786e\u7684\u90ae\u653f\u7f16\u7801"))}
function langname1_blur(){var a=$("#langname1").val();""==trim(a)?($("#langname1_span").addClass("error-tip"),$("#langname1_span").html("\u7528\u6237\u540d\u4e0d\u80fd\u4e3a\u7a7a")):isChinese(a)?($("#langname1_span").removeClass("error-tip"),$("#langname1_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e")):($("#langname1_span").addClass("error-tip"),$("#langname1_span").html(" \u8bf7\u8f93\u51651-6\u5b57\u7684\u7528\u6237\u540d\u79f0\u8c13\uff0c\u4f8b\u5982:\u8def\u6613\u5341\u4e09"))}
function contact_blur(){var a=$("#contact").val();""==trim(a)?($("#contact_span").addClass("error-tip"),$("#contact_span").html("\u8054\u7cfb\u4eba\u4e0d\u80fd\u4e3a\u7a7a")):isChinese(a)?($("#contact_span").removeClass("error-tip"),$("#contact_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e")):($("#contact_span").addClass("error-tip"),$("#contact_span").html(" \u8bf7\u8f93\u5165\u6b63\u786e\u771f\u5b9e\u8054\u7cfb\u4eba\u59d3\u540d"))}
function contel_blur(){var a=$("#contel").val();""==trim(a)?($("#contel_span").addClass("error-tip"),$("#contel_span").html("\u4e0d\u80fd\u4e3a\u7a7a")):isMobile(a)?ajaxCheckData(verifyDataUserUrl,"contel",a):($("#contel_span").addClass("error-tip"),$("#contel_span").html(" \u8bf7\u8f93\u5165\u6b63\u786e\u624b\u673a\u53f7\u7801"))}
function fax_blur(){var a=$("#fax").val();""==trim(a)?($("#fax_span").addClass("error-tip"),$("#fax_span").html("\u4e0d\u80fd\u4e3a\u7a7a")):isFax(a)?($("#fax_span").removeClass("error-tip"),$("#fax_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e")):($("#fax_span").addClass("error-tip"),$("#fax_span").html(" \u8bf7\u8f93\u5165\u6b63\u786e\u4f20\u771f\u53f7"))}
function vercheckCode(){var a=$("#ver_code").val();""==trim(a)?$("#ver_code_span").html("\u9a8c\u8bc1\u7801\u4e0d\u80fd\u4e3a\u7a7a"):(a=checkCode(a),a.check?$("#ver_code_span").html(""):($("#codechange").click(),$("#ver_code_span").addClass("error-tip"),$("#ver_code_span").html(a.message)))}
$(function(){$("#langname1").focus(function(){langname1_focus()}).blur(function(){$("#langname1").val();langname1_blur($(this))});$("#upassword").focus(function(){password_focus()}).blur(function(){password_blur($(this))});$("#upassword2").focus(function(){password2_focus()}).blur(function(){password2_blur($(this))});$("#compname").focus(function(){$("#compname_span").removeClass("error-tip");$("#compname_span").html("")}).blur(function(){unit_blur()});$("#compaddr").focus(function(){$("#compaddr_span").removeClass("error-tip");
$("#compaddr_span").html("")}).blur(function(){compaddr_blur()});$("#postcode").focus(function(){$("#postcode_span").removeClass("error-tip");$("#postcode_span").html("")}).blur(function(){postcode_blur()});$("#regcity").blur(function(){regcity_blur()});$("#contact").focus(function(){$("#contact_span").removeClass("error-tip");$("#contact_span").html("")}).blur(function(){contact_blur()});$("#contel").focus(function(){$("#contel_span").removeClass("error-tip");$("#contel_span").html("")}).blur(function(){contel_blur()});
$("#conemail").focus(function(){$("#conemail_span").removeClass("error-tip");$("#conemail_span").html("")}).blur(function(){email_blur($(this))});$("#fax").focus(function(){$("#fax_span").removeClass("error-tip");$("#fax_span").html("")}).blur(function(){fax_blur($(this))});$("#ver_code").focus(function(){$("#ver_code_span").removeClass("error-tip");$("#ver_code_span").html("")}).blur(function(){vercheckCode()});$("#btn_login").click(function(){if(!snBase.account.isBrowserSuport()||$(this).attr("disable"))return!1;
var a=checkCode($("#ver_code").val());if(!a.check)return $("#codechange").click(),$("#ver_code_span").addClass("error-tip"),$("#ver_code_span").html(a.message),!1;if(!$("#agree_check").hasClass("icons-check"))return showInfoDialog("\u8bf7\u4ed4\u7ec6\u9605\u8bfb\u300a\u670d\u52a1\u6761\u6b3e\u300b"),!1;var c={},b=!0;c.identifying=$("#ver_code").val();$("input").each(function(a,e){if($(e).attr("id")){$(e).focus();var d=$(e).attr("id");if($("#"+d+"_span").hasClass("error-tip"))return!1;var f=$("#"+
d).val();if("searchInput"!=d&&"fax"!=d&&""==f)return b=!1;f||(f="");c[d]=f}});for(a=0;2>a;a++){var e=$(".padd-tr").find("i[name\x3d'compmode']").eq(a),d=e.attr("class");if("icons-radio icons-unradio"==d){c.compmode=e.next().text();break}1==a&&"icons-radio icons-unradio"!=d&&(b=!1)}for(a=0;3>a;a++){e=$(".padd-tr").find("i[name\x3d'gbmode']").eq(a);d=e.attr("class");if("icons-radio icons-unradio"==d){c.gbmode=e.next().text();break}2==a&&"icons-radio icons-unradio"!=d&&(b=!1)}for(a=0;3>a;a++){e=$(".padd-tr").find("i[name\x3d'zbmode']").eq(a);
d=e.attr("class");if("icons-radio icons-unradio"==d){c.zbmode=e.next().text();break}2==a&&"icons-radio icons-unradio"!=d&&(b=!1)}if(!b)return showInfoDialog("\u8bf7\u5b8c\u5584\u6ce8\u518c\u4fe1\u606f\uff01"),!1;if(a=window.localStorage||window.sessionStorage)a.removeItem("SHT_INIT_Effective"),a.removeItem("SHT_INIT_Guidance");$("#btn_login").attr("disable","disable");$.ajax({url:registerUrl,type:"post",data:c,success:function(a){if("success"==a.result)if(a=getUrlPara("rollback_url"))window.location.href=
a;else{var b=snBase.account.url.userCenterUrl;b||(b=snBase.account.url.homepage);showInfoDialog2("\u606d\u559c"+$("#langname1").val()+"\uff0c\u60a8\u5df2\u6210\u529f\u6ce8\u518c\uff01");setTimeout(function(){window.location.href=b},3E3)}else showErrorMsg(a);$("#btn_login").removeAttr("disable")},dataType:"json"})})});
function showInfoDialog2(a){a="\x3cdiv class\x3d'pop-l-pc'\x3e\x3cdiv class\x3d'pop-s-pc'\x3e\x3cp\x3e"+a+"\x3c/p\x3e";a+="\x3cbutton  onclick\x3d'gotologin()'\x3e\u77e5\u9053\u4e86\x3c/button\x3e";a+="\x3c/div\x3e";a+="\x3c/div\x3e";$(".wrapper").after(a)}function gotologin(){var a=snBase.account.url.userCenterUrl;a||(a=snBase.account.url.homepage);window.location.href=a}
function getUrlPara(a){a=RegExp(a+"\x3d([^\x26]*)(\x26|$)","i");a=window.location.search.substr(1).match(a);return null!=a?unescape(a[1]):null}function getRadioValueByName(a){$("i[name\x3d'"+a+"']").each(function(a,b){if($(b).hasClass("icons-unradio"))return $(b).val()})}
function ajaxCheckData(a,c,b){$.ajax({type:"POST",url:a,data:{columnName:c,value:b},global:!1,async:!1,success:function(a){"error"==a.result?showErrorMsg(a):"contel"==c?$("#contel_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e"):"conemail"==c&&$("#conemail_span").html("\x3ci class\x3d'icons-ture'\x3e\x3c/i\x3e")},dataType:"json"})}
$("#agree_check").click(function(){$("#agree_check").hasClass("icons-check")?($("#btn_login").css("background-color","#8F8F8F"),$("#btn_login").attr("disabled","disabled")):($("#btn_login").css("background-color","#10735c"),$("#btn_login").removeAttr("disabled"))});
function showErrorMsg(a){var c=a.errcode;if(!(""==c||null==c||void 0==c))for(var c=c.split(","),b=0;b<c.length;b++)switch(c[b]){case "0004":$("#cuname").parent().parent().find(".tip").removeClass("ok").addClass("error").html("\u4f01\u4e1a/\u7528\u6237\u540d\u79f0\u5df2\u7ecf\u5b58\u5728");break;case "0005":$("#cuname").parent().parent().find(".tip").removeClass("ok").addClass("error").html("\u4f01\u4e1a/\u7528\u6237\u540d\u79f0\u5df2\u7ecf\u5b58\u5728");break;case "0001":$("#contel_span").addClass("error-tip");
$("#contel_span").html("\u624b\u673a\u53f7\u7801\u5df2\u7ecf\u5b58\u5728");break;case "0002":$("#conemail_span").addClass("error-tip");$("#conemail_span").html("\u90ae\u7bb1\u5df2\u5b58\u5728");break;case "400":showInfoDialog("\u6ce8\u518c\u5931\u8d25\uff0c\u8fde\u63a5\u7f51\u7edc\u5f02\u5e38!");break;case "401":$("#ver_code_span").addClass("error-tip");$("#ver_code_span").html("\u9a8c\u8bc1\u7801\u683c\u5f0f\u4e0d\u5bf9");break;default:showInfoDialog(a.errinfo)}};