(function(g,b){var k=g.document,n=g.navigator,o=g.location,p=Object.prototype.hasOwnProperty;b.extend=b.fn.extend=$.extend;b.extend({noConflict:function(a){g.$p===postQueryParams&&(g.$p=_$p);a&&g.snBase===b&&(g.snBase=_snBase);return b}});b.Constant={};b.toArray=function(a,b,d){if(!a||!a.length)return[];if("number"==typeof a.length){for(var f=[],c=0,g=a.length;c<g;c++)f.push(a[c]);return f.slice(b||0,d||f.length)}};b.isBoolean=function(a){return"boolean"===typeof a};b.isNumber=function(a){return"number"===
typeof a&&isFinite(a)};b.isInt=function(a){return b.isNumber(a)&&/^\-?\d+$/.test(""+a)};b.isString=function(a){return"string"===typeof a};b.isEmpty=function(a,b){return null===a||"undefined"===typeof a||a instanceof Array&&(b?!1:!a.length)||(!b?""===a:!1)};b.isNull=function(a){return null===a||"undefined"===typeof a};b.isNotNull=function(a){return!isNull(a)};b.isObject=function(a){return!!a&&"object"===typeof a};b.isPlainObject=function(a){return!!a&&a.constructor===Object};b.isFunction=function(a){return!!a&&
"function"===(typeof a).toLowerCase()};b.isArray=function(a){return!!a&&"[object Array]"===Object.prototype.toString.call(a)};b.isArrayLike=function(a){return!a||a.document||a.nodeType||b.isFunction(a)?!1:"object"===typeof a&&"number"===typeof a.length};b.isElement=function(a){return!!a&&a.nodeName&&1===a.nodeType};b.isDocument=function(a){return a.URL&&!!a.readyState};b.isWindow=function(a){return a.document&&a.navigator&&!!a.location};b.isDate=b.isDateTime=function(a){return!!a&&"[object Date]"===
toString.apply(a)};b.isPrimitive=function(a){return b.isString(a)||b.isNumber(a)||b.isBoolean(a)};b.isIterable=function(a){return b.isArray(a)||a.callee||/NodeList|HTMLCollection/.test(toString.call(a))?!0:("undefined"!=typeof a.nextNode||a.item)&&b.isNumber(a.length)};b.each=function(a,h,d){if(!b.isEmpty(a,!0)){if(!b.isIterable(a)||b.isPrimitive(a))a=[a];for(var f=0,c=a.length;f<c;f++)if(!1===h.call(d||a[f],a[f],f,a))return f}};b.iterate=function(a,h,d){if(!b.isEmpty(a))if(b.isIterable(a))b.each(a,
h,d);else if(b.isObject(a))for(var f in a)if(a.hasOwnProperty(f)&&!1===h.call(d||a,f,a[f],a))break};b.toJSON="object"===typeof JSON&&JSON.stringify?JSON.stringify:function(a){if(null===a)return"null";var h,d,f,c;c=$.type(a);if("undefined"!==c){if("number"===c||"boolean"===c)return String(a);if("string"===c)return $.quoteString(a);if("function"===typeof a.toJSON)return b.toJSON(a.toJSON());if("date"===c){h=a.getUTCMonth()+1;d=a.getUTCDate();f=a.getUTCFullYear();c=a.getUTCHours();var g=a.getUTCMinutes(),
e=a.getUTCSeconds();a=a.getUTCMilliseconds();10>h&&(h="0"+h);10>d&&(d="0"+d);10>c&&(c="0"+c);10>g&&(g="0"+g);10>e&&(e="0"+e);100>a&&(a="0"+a);10>a&&(a="0"+a);return'"'+f+"-"+h+"-"+d+"T"+c+":"+g+":"+e+"."+a+'Z"'}h=[];if($.isArray(a)){for(d=0;d<a.length;d++)h.push(b.toJSON(a[d])||"null");return"["+h.join(",")+"]"}if("object"===typeof a){for(d in a)if(p.call(a,d)){c=typeof d;if("number"===c)f='"'+d+'"';else if("string"===c)f=$.quoteString(d);else continue;c=typeof a[d];"function"!==c&&"undefined"!==
c&&(c=b.toJSON(a[d]),h.push(f+":"+c))}return"{"+h.join(",")+"}"}}};b.evalJSON="object"===typeof JSON&&JSON.parse?JSON.parse:function(a){return eval("("+a+")")};b.secureEvalJSON="object"===typeof JSON&&JSON.parse?JSON.parse:function(a){var b=a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"");if(/^[\],:{}\s]*$/.test(b))return eval("("+a+")");throw new SyntaxError("JSON\u89e3\u6790\u9519\u8bef,\u53ef\u80fd\u662fJSON\u6570\u636e\u683c\u5f0f\u4e0d\u6b63\u786e\u5f15\u8d77\u7684!");
};b.getRandom=function(){return Math.round((new Date).getTime()+1E9*Math.random())};b.getCookie=function(a,b){void 0==b&&(b=k.cookie);var d;return(d=b.match(RegExp("(^| )"+a+"\x3d([^;]*)(;|$)")))?decodeURIComponent(d[2]):null};String.prototype.endWith=function(a){return null==a||""==a||0==this.length||a.length>this.length?!1:this.substring(this.length-a.length)==a?!0:!1};String.prototype.startWith=function(a){return null==a||""==a||0==this.length||a.length>this.length?!1:this.substr(0,a.length)==
a?!0:!1};b.extend({getURLParam:function(a){if(null==a)throw Error("\u8bf7\u4f20\u5165\u9700\u8981\u53d6\u7684\u53c2\u6570\u540d!");a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?\x26]"+a+"\x3d([^\x26#]*)").exec(g.location.href);return null==a?null:a[1]},getTitle:function(){return Title=k.title},getReferrer:function(){return"string"!=typeof k.referrer?"direct":k.referrer},getRefDomain:function(){return"string"!=typeof k.referrer?"direct":b.deleteProtocolAndPortFromURL(k.referrer)},deleteProtocolAndPortFromURL:function(a){var b;
return(b=(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):null_h,a=b)?a.replace(/:\d+$/,""):a},getBrowserVersion:function(){var a,b,d,f,c,g=n.userAgent.toLowerCase(),e;(e=g.match(/msie ([\d.]+)/))?a=e[1]:(e=g.match(/firefox\/([\d.]+)/))?b=e[1]:(e=g.match(/chrome\/([\d.]+)/))?d=e[1]:(e=g.match(/opera.([\d.]+)/))?f=e[1]:(e=g.match(/version\/([\d.]+).*safari/))?c=e[1]:0;return a?"msie "+a:b?"firefox "+b:d?"chrome "+d:f?"opera "+f:c?"safari "+c:"Unknown browser version."},getScreenSize:function(){return g.screen.width+
"x"+g.screen.height},getUrlFileName:function(a){a=(a||k.location.href).split("/");if(""==a[a.length-1]||null==a[a.length-1])return"default.html";a=a[a.length-1];var b=a.indexOf("?");0>b&&(b=a.indexOf("#"));0<b&&(a=a.substring(0,b));return a},getSiteId:function(a){a=b.getUrlFileName(a);if(0>a.indexOf("~"))return"";a=a.split("~");return 0<a.length?a[0]:""},getPageId:function(a){a=b.getUrlFileName(a);if(0>a.indexOf("~"))return"";a=a.split("~");return 1<a.length?a[1]:""},getChannelId:function(a){a=b.getUrlFileName(a);
if(0>a.indexOf("~"))return"";a=a.split("~");return 2<a.length?a[2]:""},getAdditionaParameter:function(a){a=b.getUrlFileName(a);if(0>a.indexOf("~"))return"";a=a.split("~");return 4<a.length?a[4]:""},getCookie:function(a){a=RegExp("(^|)"+a+"\x3d([^;]*)(;|$)").exec(k.cookie);return null!=a?decodeURIComponent(a[2]):null},setCookie:function(a,b){var d=a+"\x3d"+encodeURIComponent(b);k.cookie=d},analysisPageParams:function(a){if(g._pageParamObject)return g._pageParamObject;var h={};if(a){var d=a.indexOf("?"),
f=[];if(0>d)f=a.split("-");else{var c=a.substring(0,d);if(null!=c&&0<c.length)for(var i=c.split("-"),c=0;c<i.length;c++)f.push(i[c]);c=a.substring(d+1);if(null!=c&&0<c.length){a=c.split("-");for(c=0;c<a.length;c++)f.push(a[c])}}}if(null!=f&&0<f.length){if(c=b.getUrlFileName(k.location.href))a=c.lastIndexOf("."),0<=a&&(c=c.substring(0,a));c=c.split("~");c=4<c.length?c[4]:null;a=null==c?[]:c.split("-");for(c=0;c<f.length;c++)d=this.getURLParam(f[c]),h[f[c]]=null==d?void 0===a[c]?null:a[c]:d}return g._pageParamObject=
h},postCollectedInfo:function(a,h,d){var f=g._collectorArguments;if(!f)return{};if(g.self!=g.top&&!d)return null;if(null==h||""==h||"null"==h.toLowerCase())if((d=f.collectorServer)&&(h=d+"rest/collector/updateinfo.do"),null==h||""==h||"null"==h.toLowerCase())throw Error("\u8bf7\u5728Config\u4e2d\u914d\u7f6e\u4fe1\u606f\u6536\u96c6\u670d\u52a1\u5668\u7684\u5730\u5740!");d=null;f&&((d=f.wsp)||(d=b.getURLParam(d)));var c=f.siteId,i=f.pageId,e=f.releaseName;d=f.parameFormat;null!=a&&"string"==typeof a&&
(a=b.evalJSON(a));if(!a||"error"==a.restlt)a={};var l=a.collectIdArr,f=a.urlparamsArr;a=a.cookiesArr;var j={};j.baseInfo={siteId:c,pageId:i,releaseName:e};var e=g.location.href,m=null;g.sessionStorage?(m=g.sessionStorage.getItem("sn_collector_lastPage"),g.sessionStorage.setItem("sn_collector_lastPage",e)):(m=b.getCookie("sn_collector_lastPage"),b.setCookie("sn_collector_lastPage",e));var n=b.getSiteId(m),m=b.getPageId(m);j.pageInfo={refSiteId:n,refPageId:m,title:b.getTitle(),browser:b.getBrowserVersion(),
screen:b.getScreenSize(),refDomain:b.getRefDomain(),refPage:b.getReferrer(),pageDomain:b.deleteProtocolAndPortFromURL(e),pageUrl:k.location.href,pageFile:b.getUrlFileName(e),siteId:c||b.getSiteId(e),pageId:i||b.getPageId(e)};g.nativeAPI&&g.nativeAPI.sys&&g.nativeAPI.sys.getSessionVal?(c=g.nativeAPI.sys.getSessionVal("batchNo"),c||((c=(new Date).getTime())&&(c+=""),g.nativeAPI.sys.setSessionVal("batchNo",c))):(c=b.getCookie("batchNo"),c||(c=(new Date).getTime(),b.setCookie("batchNo",c)));j.pageInfo.batchNo=
c||0;j.dataInfo={};if(null!=l&&0<l.length)for(c=0;c<l.length;c++)i=l[c],i=$("[collectId \x3d "+i+"]"),null!=i&&(e=i.getAttribute("collectId"),j.dataInfo[e]=i.value||i.innerHTML);else l=$("[collectId]"),null!=l&&$(l).each(function(a,b){var c=b.getAttribute("collectId");j.dataInfo[c]=b.value||b.innerHTML});j.paramsInfo=b.analysisPageParams(d)||{};j.cookiesInfo={};if(null!=a&&0<a.length)for(c=0;c<a.length;c++)d=a[c],j.cookiesInfo[d]=b.getCookie(d);j.cookiesInfo.UUIDKEYVALUE=b.getCookie("UUIDKEYVALUE");
j.cookiesInfo.B_UUIDKEYVALUE=b.getCookie("B_UUIDKEYVALUE");j.urlParamsInfo={};if(null!=f&&0<f.length)for(c=0;c<f.length;c++)i=f[c],j.urlParamsInfo[i]=b.getURLParam(i);j.deviceInfo={};g.nativeAPI&&(j.deviceInfo.deviceType=g.nativeAPI.deviceType,j.deviceInfo.uuid=g.nativeAPI.sys.getUuid(),g.nativeAPI.sys.getIMEI&&(j.deviceInfo.IMEI=g.nativeAPI.sys.getIMEI()),j.deviceInfo.oldVer=g.nativeAPI.sys.getOldAppVersion(),j.deviceInfo.ver=g.nativeAPI.sys.getAppVersion(),j.deviceInfo.osVer=g.nativeAPI.sys.getOSVersion());
$.post(h,{info:b.toJSON(j)},function(a,b){console&&console.log("\u6536\u96c6\u4fe1\u606f\u5df2\u63d0\u4ea4:"+a+","+b)},"json");return j},updateClickInfo:function(a,h,d,f){if(g.self!=g.top&&!f)return{};f=g._collectorArguments;if(null==d||""==d||"null"==d.toLowerCase()){if(f){var c=f.collectorServer;c&&(d=c+"rest/collector/postclickinfo.do")}if(!d||""==d||"null"==d.toLowerCase())return{}}var i=null;f&&((i=f.wsp)||(i=b.getURLParam(i)));null!=h&&"string"==typeof h&&(h=b.evalJSON(h));if(!h||"error"==h.restlt)return{};
f=h.urlparamsArr;c=h.cookiesArr;def_id=h.def_id;var e={};null!=i&&0<i.length&&(e.wsp=i);null!=def_id&&0<def_id.length&&(e.def_id=def_id);e.params=a;e.pageInfo={};e.pageInfo.browser=b.getBrowserVersion();e.deviceInfo={};g.nativeAPI&&(e.deviceInfo.deviceType=g.nativeAPI.deviceType,e.deviceInfo.uuid=g.nativeAPI.sys.getUuid(),g.nativeAPI.sys.getIMEI&&(e.deviceInfo.IMEI=g.nativeAPI.sys.getIMEI()),e.deviceInfo.osVer=g.nativeAPI.sys.getOSVersion());e.cookiesInfo={};if(null!=c&&0<c.length)for(a=0;a<c.length;a++)h=
c[a],cookiesInfo[h]=b.getCookie(h);e.cookiesInfo.UUIDKEYVALUE=b.getCookie("UUIDKEYVALUE");e.cookiesInfo.B_UUIDKEYVALUE=b.getCookie("B_UUIDKEYVALUE");e.urlParamsInfo={};null!=f&&0<f.length&&f.each(function(a){e.urlParamsInfo[a]=b.getURLParam(a)});$.post(d,{info:b.toJSON(e)},function(a,b){console&&console.log("\u6536\u96c6\u4fe1\u606f\u5df2\u63d0\u4ea4:"+a+","+b)},"json");return e}});b.image={url:{ajaxDataUrl:"",webSiteUrl:""},defaultimg:null,getHandleDefaultImg:function(a){if("nodata"==this.defaultimg||
!a)return null;this.defaultimg||this.loadDefaultImg();return this.defaultimg&&this.defaultimg[a]?this.url.webSiteUrl+"/"+this.defaultimg[a]:null},loadDefaultImg:function(){$.ajax({type:"GET",dataType:"json",url:this.url.ajaxDataUrl,data:{},async:!1,success:function(a){b.image.defaultimg=a?a:"nodata"}})},onImageError:function(a){if(a){var b=event.srcElement||event.target;"IMG"==b.tagName&&(b.onerror=null,b.src=a)}}};b.enc={charSet:"",browsetType:"",getBrowser:function(){-1!=n.userAgent.indexOf("MSIE")?
this.browsetType="IE":-1!=n.userAgent.indexOf("Firefox")&&(this.browsetType="FIREFOX");return this.browsetType},getPageCharset:function(){switch(this.getBrowser()){case "IE":this.charSet=k.charset;break;case "FIREFOX":this.charSet=k.characterSet;break;default:this.charSet=k.characterSet}return this.charSet}};b.localData={hname:o.hostname?o.hostname:"localStatus",isLocalStorage:g.localStorage?!0:!1,dataDom:null,initDom:function(){if(!this.dataDom)try{this.dataDom=k.createElement("input"),this.dataDom.type=
"hidden",this.dataDom.style.display="none",this.dataDom.addBehavior("#default#userData"),(k.body||k.getElementsByTagName("head")[0]||k.documentElement).appendChild(this.dataDom)}catch(a){return!1}return!0},set:function(a,b){this.isLocalStorage?g.localStorage.setItem(a,b):this.initDom()&&(this.dataDom.load(this.hname),this.dataDom.setAttribute(a,b),this.dataDom.save(this.hname))},get:function(a){if(this.isLocalStorage)return g.localStorage.getItem(a);if(this.initDom())return this.dataDom.load(this.hname),
this.dataDom.getAttribute(a)},remove:function(a){this.isLocalStorage?localStorage.removeItem(a):this.initDom()&&(this.dataDom.load(this.hname),this.dataDom.removeAttribute(a),this.dataDom.save(this.hname))}};b.base64encode=function(a){var b,d,f,c;b="";f=a.length;for(d=0;d<f;d++)c=a.charCodeAt(d),1<=c&&127>=c?b+=a.charAt(d):(2047<c?(b+=String.fromCharCode(224|c>>12&15),b+=String.fromCharCode(128|c>>6&63)):b+=String.fromCharCode(192|c>>6&31),b+=String.fromCharCode(128|c>>0&63));var g;f=b.length;d=0;
for(var e="";d<f;){a=b.charCodeAt(d++)&255;if(d==f){e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>2);e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((a&3)<<4);e+="\x3d\x3d";break}c=b.charCodeAt(d++);if(d==f){e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>2);e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((a&3)<<4|(c&240)>>4);e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((c&
15)<<2);e+="\x3d";break}g=b.charCodeAt(d++);e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>2);e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((a&3)<<4|(c&240)>>4);e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((c&15)<<2|(g&192)>>6);e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g&63)}return e};"function"===typeof define&&(define.amd&&define.amd.snBase)&&define("postQueryParams",
[],function(){return b})})(window,snBase);